### ISSUE TITLE
Bump openssl dependency

### ISSUE THREAD

**Issue by kpcyrd** [faradayio/boondock#13]
This is a headsup that the current openssl dependency is outdated and doesn't compile on my system anymore. :) I'm currently on openssl 1.1.0.g

**Comment by emk** [comment]
Thank you for letting me know!

I went to take a look at the `Cargo.toml` file, and I found this:

```toml
[dependencies]
error-chain = "0.5.0"
hyper = { version = "0.9", default-features = false }
openssl = { version = "0.7", optional = true }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.2.2"
```

In order to fix this, we need to replace `hyper` and `openssl` with [`reqwest`](https://docs.rs/reqwest/0.8.1/reqwest/), which has a fairly similar synchronous API. Unfortunately, I don't have time to work on that this week, but I'd be happy to help somebody prepare a PR and get it merged.

For a short-term fix, it's possible to build static binaries using my https://github.com/emk/rust-musl-builder Docker image, which worked with boondock the last time I tried.
